// Generated by CoffeeScript 1.9.2
(function() {
  $('a[href^=#]').click(function() {
    var href, position, speed, target;
    speed = 500;
    href = $(this).attr('href');
    target = $(href === '#' || href === '' ? 'html' : href);
    position = target.offset().top;
    $('html, body').animate({
      scrollTop: position
    }, speed, 'swing');
    return false;
  });

  return;

}).call(this);
